### ISSUE TITLE
实施问题

### ISSUE THREAD

**Issue by MapTracy** [momosecurity/cornerstone#2]

**Comment by MapTracy** [comment]
在/etc/bashrc中加载该文件，如[ -f /etc/momosec_bashrc ] && . /etc/momosec_bashrc
这一步骤是怎么做呢？能麻烦具体告诉一下吗？

**Comment by kkilloas** [comment]
就是把这行追加到/etc/bashrc中即可，比如在命令行中echo '[ -f /etc/momosec_bashrc ] && . /etc/momosec_bashrc' >> /etc/bashrc
