### ISSUE TITLE
脚本使用请教几个问题

### ISSUE THREAD

**Issue by orright** [momosecurity/cornerstone#5]
首先非常感谢陌陌安全团队的贡献，这个脚本很有用
然后我想请教2个问题  

1.  /var/log/messages  日志应该存在写入速率限制，陌陌是如何解决的呢？
2.  vim内执行命令的审计，我看了公众号上的文章说是可以审计的，但我简单测试了下，没有效果，具体是指的什么内容呢？

**Comment by kkilloas** [comment]
1. /var/log/messages 这个的写入速率限制当时并没有考虑到，可能运维同学帮忙解决了吧
2. 比如说vi test进入到test文件，然后输入:!ls回车，就会记录到执行了ls命令

**Comment by orright** [comment]
> 1. /var/log/messages 这个的写入速率限制当时并没有考虑到，可能运维同学帮忙解决了吧
> 2. 比如说vi test进入到test文件，然后输入:!ls回车，就会记录到执行了ls命令

感谢回复哈
