### ISSUE TITLE
关于冰蝎或者哥斯拉的远程执行命令，我测试了下似乎没有办法审计到！

### ISSUE THREAD

**Issue by orright** [momosecurity/cornerstone#6]
关于冰蝎或者哥斯拉的远程执行命令，我测试了下似乎没有办法审计到！

不知道有时间的化，能否帮忙看看，有没有办法，我看了下都是no tty的环境

**Comment by kkilloas** [comment]
对于应用内的命令执行理论上是无法审计的，像php python等命令执行的函数所执行的都无法审计

**Comment by orright** [comment]
感谢回复
