### ISSUE TITLE
可以在zshrc上配置 并且在zsh上执行吗？

### ISSUE THREAD

**Issue by kkmg112400** [momosecurity/cornerstone#7]

**Comment by kkilloas** [comment]
不能直接使用。需要对一些命令/路径做修改；另外还需要测试下trap debug在bash和zsh上的差异

**Comment by kkmg112400** [comment]
> 不能直接使用。需要对一些命令/路径做修改；另外还需要测试下trap debug在bash和zsh上的差异

3Q
